import { Inter } from "next/font/google";
import Head from "next/head";
// import { config } from "@fortawesome/fontawesome-svg-core";
// import "@fortawesome/fontawesome-svg-core/styles.css";
// config.autoAddCss = false;
// import "@fortawesome/fontawesome-free/css/all.min.css";
import "react-toastify/dist/ReactToastify.css";
import "../../public/css/adminpanelstyle.css"
import "../../public/css/pdftemplatestyle.css"
import "../../public/css/style.css"
import "../../public/plugins/slick/slick.css"
import "../../public/plugins/slick/slick-theme.css"
import "../../public/plugins/fancybox/jquery.fancybox.min.css";
import "../../public/plugins/slick/slick-theme.css"
// import "../../public/css/adminpanelstyle.css";
// import "../../public/css/style.css";
import Script from "next/script";
import { ToastContainer } from "react-toastify";
import Authprovider from "@/components/Authprovider/Authprovider";

const inter = Inter({ subsets: ["latin"] });
export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      {/* <!-- slider stylesheet --> */}
      {/* <!-- Slick Carousel --> */}
      {/* <link rel="stylesheet" href="plugins/slick/slick.css" /> */}
      {/* <link rel="stylesheet" href="plugins/slick/slick-theme.css" /> */}
      {/* <!-- FancyBox --> */}
      {/* <link rel="stylesheet" href="plugins/fancybox/jquery.fancybox.min.css" /> */}

      {/* <!--Favicon--> */}
      <link rel="shortcut icon" href="images/favicon.ico" type="image/x-icon" />
      <link rel="icon" href="images/favicon.ico" type="image/x-icon" />

      <body className={inter.className}>
        <Authprovider>
          {children}
        </Authprovider>
        <ToastContainer
          position="top-center"
          autoClose={5000}
          hideProgressBar={false}
          newestOnTop={false}
          closeOnClick
          rtl={false}
          pauseOnFocusLoss
          draggable
          pauseOnHover
          theme="light"
        />
      </body>
      <Script src="plugins/jquery.js"></Script>
      <Script src="plugins/bootstrap.min.js"></Script>
      <Script src="plugins/bootstrap-select.min.js"></Script>
      {/* <!-- Slick Slider --> */}
      <Script src="plugins/slick/slick.min.js"></Script>
      {/* <!-- FancyBox --> */}
      <Script src="plugins/fancybox/jquery.fancybox.min.js"></Script>
      {/* <!-- Google Map --> */}
      <Script src="https://maps.googleapis.com/maps/api/js?key=AIzaSyCC72vZw-6tGqFyRhhg5CkF2fqfILn2Tsw"></Script>
      {/* <Script src="plugins/google-map/gmap.js"></Script> */}

      <Script src="plugins/validate.js"></Script>
      <Script src="plugins/wow.js"></Script>
      <Script src="plugins/jquery-ui.js"></Script>
      <Script src="plugins/timePicker.js"></Script>
      <Script src="js/script.js"></Script>
    </html>
  );
}
